#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
echo "Copying $OPENSHIFT_REPO_DIR/.htaccess to $OPENSHIFT_DATA_DIR/current/."
cp $OPENSHIFT_REPO_DIR/.htaccess $OPENSHIFT_DATA_DIR/current/.
